In [ ]:
normalize1 = array / np.linalg.norm(array)

In [3]:
import numpy as np

In [19]:
a = np.array([[10,20,30],[40,50,60],[70,80,90]])
print(a)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [11]:
a = a / np.linalg.norm(10)
print(a)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [ ]:
a/=10.0
print(a)

In [22]:
a = a / 10
print(a)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [ ]:
        self.sample = np.array(Image.open(io.BytesIO(sample)).resize((224,224),))
#         self.sample = np.array(Image.open(io.BytesIO(sample)))
#         self.sample = sample
#         self.sample = self.sample / 255.0

In [1]:
# The Sample Extractor

import os
import time
import shutil
import glob

def extractFiles(storagePath, sampleFile, subFolder=''):
    
    # Setup path variables
    copyName = 'Extractable_'+(time.strftime("%m%d%y_%H%M%S", time.gmtime()))
    copyPath = storagePath+copyName
    zipPath = storagePath+subFolder+copyName
    transferredFiles = glob.glob(storagePath+sampleFile+'/*')
    
    # copyPath Needs to be storage/extraction/
    
    # Copy files from src to destination
    shutil.copytree((storagePath+sampleFile), copyPath)
    
    # Zip temporary files into target location
    try:
        shutil.make_archive(zipPath, 'zip', storagePath, copyName)
    except OSError:
        pass
    
    # Clean up transferred Images
    for f in transferredFiles:
        os.remove(f)
        
    # Clean up tempory file
    shutil.rmtree(copyPath)
    
    return


extractFiles('data/','sampleImages','extraction/')

In [ ]:
# version 2
import os
import zipfile
import time
import shutil
import glob

def extractFiles(path):
    transferredFiles = glob.glob(path+'/*')
    zipName = 'Extractable_'+(time.strftime("%m%d%y_%H%M%S", time.localtime()))+'.zip'
    zipf = zipfile.ZipFile(zipName, 'w', zipfile.ZIP_DEFLATED)
    for root, dirs, files in os.walk(path):
        for file in files:
            zipf.write(os.path.join(root, file))
    zipf.close()
    # Clean up transferred Images
    for f in transferredFiles:
        shutil.rmtree(f)
    return

In [ ]:
extractFiles('extraction')

In [ ]:
os.path.exists('/home/pi/LockCam/data/sampleImages')

In [ ]:
os.path.relpath('/home/pi/LockCam/data/sampleImages')

In [ ]:
os.path.exists('sampleImages')

In [ ]:
# ### This command works to copy zipped files from remote raspberry to local windows machine (RUN ON WINDOWS CMD LINE)
# scp pi@10.0.0.201:/home/pi/CameraProject/extraction/*  C:/Users/micha/Desktop/UnsortedImages

In [ ]:
# ### This command works to copy all files from remote raspberry to local windows machine (RUN ON WINDOWS CMD LINE)
# scp pi@10.0.0.201:/home/pi/CameraProject/sampleImages/*  C:/Users/micha/Desktop/UnsortedImages

In [ ]:
# ## Image Copier for making test backups
# !cp -r /home/pi/CameraProject/sampleImagesBackup/* /home/pi/CameraProject/sampleImages/